# Generated by Django 5.1.2 on 2024-11-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241120_2145'),
    ]

    operations = [
    ]
