# Generated by Django 4.2.16 on 2024-11-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241121_0347'),
    ]

    operations = [
    ]
