# Generated by Django 4.2.16 on 2024-11-21 01:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('attention', '0002_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('sangre', 'Análisis de Sangre'), ('orina', 'Análisis de Orina'), ('rayosx', 'Rayos X'), ('tomografia', 'Tomografía'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Examen')),
                ('estado', models.CharField(choices=[('PENDITE', 'Pendiente'), ('PROCESADO', 'Procesando'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del Examen')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Realización')),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='examenes/resultados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo de Resultado (PDF)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Examen')),
                ('observaciones_doctor', models.TextField(blank=True, null=True, verbose_name='Observaciones del Doctor')),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='attention.atencion')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='core.doctor')),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
