# Generated by Django 4.2.16 on 2024-11-22 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0004_examen_curriculum_alter_examen_archivo_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costoatenciondetalle',
            name='costo_atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_atenciones', to='attention.costosatencion', verbose_name='Costo Atención'),
        ),
        migrations.AlterField(
            model_name='costoatenciondetalle',
            name='servicios_adicionales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='attention.serviciosadicionales', verbose_name='Servicios Adicionales'),
        ),
    ]
